set runtimepath^=~/.config/vim
set runtimepath+=~/.config/vim/after

let mapleader=" "
let maplocalleader=" "
let g:have_nerd_font = 1

set number
set relativenumber
set hlsearch
set smartindent
set mouse=a
set noshowmode
set breakindent
set undofile
set ignorecase
set smartcase
set updatetime=250
set timeoutlen=300
set splitright
set splitbelow
set list
set listchars=tab:»\ ,trail:·,nbsp:␣
set scrolloff=10
set confirm

inoremap jk <Esc>
nnoremap <Esc> :nohlsearch<CR>
nnoremap <C-p> :<C-u>FZF<CR>
nnoremap <silent> <leader>s :w<CR>
nnoremap <Leader><Tab> <C-^>
nnoremap <Leader>y "+y
nnoremap <Leader>Y "+Y
nnoremap <Leader>p "+p
nnoremap <Leader>P "+P
nnoremap [q :cprev<CR>
nnoremap ]q :cnext<CR>
nnoremap [Q :cfirst<CR>
nnoremap ]Q :clast<CR>
nnoremap [<C-q> :copen<CR>
nnoremap ]<C-q> :cclose<CR>
nnoremap <C-h> <C-w><C-h>
nnoremap <C-l> <C-w><C-l>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>

vnoremap <Leader>y "+y
vnoremap <Leader>Y "+Y
vnoremap <Leader>p "+p
vnoremap <Leader>P "+P
vnoremap <Leader>s :w<CR>
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Only load in Vim, not NeoVim
if !has('nvim')
	command! PackUpdate call minpac#update()
	command! PackClean call minpac#clean()

	packadd minpac
	call minpac#init()
	call minpac#add('t-takata/minpac', {'type': 'opt'})
	call minpac#add('tpope/vim-unimpaired')
	call minpac#add('tpope/vim-surround')
	call minpac#add('junegunn/fzf')
	call minpac#add('tpope/vim-dispatch')
	call minpac#add('tpope/vim-scriptease', {'type': 'opt'})
endif
